POST http://localhost:4000/todolist/signup
Content-Type: application/json

{
    "firstName":"Ramil",
    "username":"Invisible",
    "email":"allahverdiyevramil@yahoo.com",
    "password":"ToDoListqagassa"
}